server:
  port: 9001
  servlet:
    context-path: /bona-fide-user-service

jwt:
  secret: bona-fide
  enabled: true

spring:
  main:
    allow-circular-references: true
  data:
    cassandra:
      port: 9042
      contact-points: cassandra
      keyspace-name: productkeyspace